### ISSUE TITLE
stream dropped after return

### ISSUE THREAD

**Issue by ericmccarthy7** [Protryon/klickhouse#20] opened 2023-04-26 03:41 UTC
In this example I attempt to pass the stream out of the function via a return value. It seems that it is immediately dropped when I do this?

I'm new-ish to rust so maybe this is just a lack of understanding.

```rust
use futures::stream::{Stream, StreamExt};

#[tokio::main]
async fn main() {
    let client =
        klickhouse::Client::connect("127.0.0.1:9000", klickhouse::ClientOptions::default())
            .await
            .unwrap();

    let mut res = stream(client).await;

    while let Some(row) = res.next().await {
        let row = row.unwrap();
        println!("row received {:?}", row);
    }
}

#[derive(klickhouse::Row, Debug, Default)]
pub struct MyUserData {
    x: String,
    y: String,
}

async fn stream(
    client: klickhouse::Client,
) -> impl Stream<Item = Result<MyUserData, klickhouse::KlickhouseError>> {
    let all_rows = client
        .query::<MyUserData>("select x, toTypeName(x) AS y from t1;")
        .await
        .unwrap();
    all_rows
}
```

Expected output:
```
row received MyUserData { x: "1", y: "String" }
row received MyUserData { x: "2", y: "String" }
```

Actual output:
```
```

If I rerun it with the print statement inside the other function it works.

```rust
use futures::stream::{Stream, StreamExt};

#[tokio::main]
async fn main() {
    let client =
        klickhouse::Client::connect("127.0.0.1:9000", klickhouse::ClientOptions::default())
            .await
            .unwrap();

    let _ = stream(client).await;
}

#[derive(klickhouse::Row, Debug, Default)]
pub struct MyUserData {
    x: String,
    y: String,
}

async fn stream(
    client: klickhouse::Client,
) -> impl Stream<Item = Result<MyUserData, klickhouse::KlickhouseError>> {
    let mut all_rows = client
        .query::<MyUserData>("select x, toTypeName(x) AS y from t1;")
        .await
        .unwrap();
    while let Some(row) = all_rows.next().await {
        let row = row.unwrap();
        println!("row received {:?}", row);
    }
    all_rows
}
```

Output:

```
row received MyUserData { x: "1", y: "String" }
row received MyUserData { x: "2", y: "String" }
```

FYI values in clickhouse:

```
SELECT *
FROM t1

┌─x─┐
│ 1 │
└───┘
┌─x─┐
│ 2 │
└───┘

2 rows in set. Elapsed: 0.021 sec.
```

**Comment by Protryon** [comment] 2023-04-26 16:41
I think the issue here is that your `main` fn is exiting too quickly after the `println`? I've seen that before with async, maybe add a 100ms `tokio::time::sleep` before your main fn terminates, and see if that fixes the issue.

When running in the function, there's an extra indirection of going through the executor.

Just a guess though, this code should absolutely work under normal circumstances. Let me know if this doesn't solve it.

**Comment by ericmccarthy7** [comment] 2023-04-26 22:51
Hm.. this didn't solve it.

```rust
use futures::stream::{Stream, StreamExt};

#[tokio::main]
async fn main() {
    let client =
        klickhouse::Client::connect("127.0.0.1:9000", klickhouse::ClientOptions::default())
            .await
            .unwrap();

    let mut res = stream(client).await;

    while let Some(row) = res.next().await {
        let row = row.unwrap();
        println!("row received {:?}", row);
    }
    tokio::time::sleep(tokio::time::Duration::from_secs(1)).await;
}

#[derive(klickhouse::Row, Debug, Default)]
pub struct MyUserData {
    x: String,
    y: String,
}

async fn stream(
    client: klickhouse::Client,
) -> impl Stream<Item = Result<MyUserData, klickhouse::KlickhouseError>> {
    let all_rows = client
        .query::<MyUserData>("select x, toTypeName(x) AS y from t1;")
        .await
        .unwrap();
    all_rows
}
```

Is it possible because of `Note that no rows are returned until Clickhouse sends a full block (but it usually sends more than one block).`

Maybe there's a problem with the logic of waiting for a block?

Even weirder, if I do this:

```rust
async fn stream(
    client: klickhouse::Client,
) -> impl Stream<Item = Result<MyUserData, klickhouse::KlickhouseError>> {
    let mut all_rows = client
        .query::<MyUserData>("select x, toTypeName(x) AS y from t1;")
        .await
        .unwrap();
    all_rows.next().await;
    all_rows
}
```

It does give me back a stream with the remaining rows.

**Comment by Protryon** [comment] 2023-04-27 19:15
I think I see what the problem is.

I have an architectural solution in mind to avoid it (that I will implement in the next few days), but the TL;DR is that the `Client` cannot be dropped while waiting for blocks. It's essentially the network handle, and if it gets dropped, any streams waiting on it will EOF.

This behavior might actually be ideal since it allows for easy closing, but definitely needs to be better documented/implemented.

**Comment by Protryon** [comment] 2023-07-09 20:09
Looking back on this later, I realized that this behavior is a consistent design pattern with `tokio-postgres` and the `Connection` object. Dropping the `Client` should, IMO, drop any pending streams. I'm open to other opinions though.

**Closed by Protryon** 2023-07-09 20:09 UTC
